name: Waka Readme

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
